using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Media;

namespace UWPCore.Framework.Common
{
    /// <summary>
    /// Enumeration of all glyph icons.
    /// </summary>
    /// <remarks>
    /// Some icons are still missing!
    /// Check out: <see cref="http://modernicons.io/segoe-mdl2/cheatsheet/"/> and add more when needed.
    /// </remarks>
    public enum GlyphIcons
    {
        Account = 0xEA8C,
        AccountBox = 0xE187,
        AccountCancel = 0xE1E0,
        AccountDetailsOutline = 0xE136,
        AccountFrameOutline = 0xE156,
        AccountMultiple = 0xE125,
        AccountOutline = 0xE13D,
        AccountOutlineBox = 0xE8D4,
        AccountPlus = 0xE1E2,
        AccountStatus = 0xE181,
        AccountSwitch = 0xE748,
        ActionCenter = 0xEC42,
        Airplane = 0xEB4C,
        AirplaneOutline = 0xE709,
        Album = 0xE142,
        Alert = 0xE814,
        AlertOutline = 0xE7BA,
        AllApps = 0xE71D,
        Archive = 0xE7B8,
        Archive2 = 0xE7B7,
        Flag = 0xE7C1,
        Arrow = 0xE1D1,
        ArrowBottomRight = 0xE741,
        ArrowDown = 0xE1FD,
        ArrowLeft = 0xE0A6,
        ArrowRight = 0xE0AD,
        ArrowTopLeft = 0xE742,
        ArrowUp = 0xE110,
        ArrowUpVariant = 0xE752,
        Attach = 0xE16C,
        Bag = 0xE14D,
        Battery0 = 0xE850,
        Battery1 = 0xE851,
        Battery10 = 0xE83F,
        Battery2 = 0xE852,
        Battery3 = 0xE853,
        Battery4 = 0xE854,
        Battery5 = 0xE855,
        Battery6 = 0xE856,
        Battery7 = 0xE857,
        Battery8 = 0xE858,
        Battery9 = 0xE859,
        BatteryCharge0 = 0xE85A,
        BatteryCharge1 = 0xE85B,
        BatteryCharge2 = 0xE85C,
        BatteryCharge3 = 0xE85D,
        BatteryCharge4 = 0xE85E,
        BatteryCharge5 = 0xE85F,
        BatteryCharge6 = 0xE860,
        BatteryCharge7 = 0xE861,
        BatteryCharge8 = 0xE862,
        BatteryDisconnect = 0xE996,
        BatteryLarge0 = 0xEBA0,
        BatteryLarge1 = 0xEBA1,
        BatteryLarge10 = 0xEBAA,
        BatteryLarge2 = 0xEBA2,
        BatteryLarge3 = 0xEBA3,
        BatteryLarge4 = 0xEBA4,
        BatteryLarge5 = 0xEBA5,
        BatteryLarge6 = 0xEBA6,
        BatteryLarge7 = 0xEBA7,
        BatteryLarge8 = 0xEBA8,
        BatteryLarge9 = 0xEBA9,
        BatteryLargeCharge0 = 0xEBAB,
        BatteryLargeCharge1 = 0xEBAC,
        BatteryLargeCharge10 = 0xEBB5,
        BatteryLargeCharge2 = 0xEBAD,
        BatteryLargeCharge3 = 0xEBAE,
        BatteryLargeCharge4 = 0xEBAF,
        BatteryLargeCharge5 = 0xEBB0,
        BatteryLargeCharge6 = 0xEBB1,
        BatteryLargeCharge7 = 0xEBB2,
        BatteryLargeCharge8 = 0xEBB3,
        BatteryLargeCharge9 = 0xEBB4,
        BatteryLargeSave0 = 0xEBB6,
        BatteryLargeSave1 = 0xEBB7,
        BatteryLargeSave10 = 0xEBC0,
        BatteryLargeSave2 = 0xEBB8,
        BatteryLargeSave3 = 0xEBB9,
        BatteryLargeSave4 = 0xEBBA,
        BatteryLargeSave5 = 0xEBBB,
        BatteryLargeSave6 = 0xEBBC,
        BatteryLargeSave7 = 0xEBBD,
        BatteryLargeSave8 = 0xEBBE,
        BatteryLargeSave9 = 0xEBBF,
        BatterySave0 = 0xE863,
        BatterySave1 = 0xE864,
        BatterySave2 = 0xE865,
        BatterySave3 = 0xE866,
        BatterySave4 = 0xE867,
        BatterySave5 = 0xE868,
        BatterySave6 = 0xE869,
        BatterySave7 = 0xE86A,
        BatterySave8 = 0xE86B,
        BellOffOutline = 0xE7ED,
        BellOutline = 0xEA8F,
        Bluetooth = 0xE702,
        Boat = 0xEB48,
        BoatOutline = 0xE7E3,
        Book = 0xE82D,
        BookPlus = 0xE82E,
        BoxFourth = 0xE744,
        BoxFull = 0xE747,
        BoxHalfHorizontal = 0xE745,
        BoxHalfVertical = 0xE746,
        BoxSixteenth = 0xE743,
        BoxSmall = 0xE004,
        BrowsePhotos = 0xE7C5,
        Bus = 0xEB47,
        BusOutline = 0xE806,
        Calculator = 0xE1D0,
        Calendar = 0xE163,
        CalendarDay = 0xE184,
        CalendarRepeat = 0xE161,
        CalendarReply = 0xE1DB,
        CalendarWeeks = 0xE162,
        Camera = 0xE114,
        CameraClicker = 0xE12D,
        CameraSwitch = 0xE124,
        Cancel = 0xE25B,
        Car = 0xE7EC,
        CarLeftOutline = 0xE811,
        CarRightOutline = 0xEA5E,
        CarSide = 0xEA8B,
        Cd = 0xE958,
        Cellphone = 0xE1C9,
        CellphoneTablet = 0xE8CC,
        CellphoneWireless = 0xE957,
        Check = 0xE001,
        CheckboxBlank = 0xE002,
        CheckboxBlankOutline = 0xE003,
        CheckboxCheck = 0xE005,
        CheckOutlineCheck = 0xE0A2,
        ChevronBoldDown = 0xE96E,
        ChevronBoldLeft = 0xE96F,
        ChevronBoldRight = 0xE970,
        ChevronBoldUp = 0xE96D,
        ChevronDown = 0xE011,
        ChevronLeft = 0xE00E,
        ChevronLeftCircle = 0xE760,
        ChevronRight = 0xE00F,
        ChevronRightCircle = 0xE761,
        ChevronUp = 0xE010,
        Chip = 0xE964,
        Clear = 0xE750,
        ClearSmall = 0xE925,
        Clipboard = 0xE77F,
        Clock = 0xE121,
        Close = 0xE106,
        ClosedCaption = 0xE190,
        Cloud = 0xE753,
        Compare = 0xE11E,
        Computer = 0xE211,
        ComputerTheme = 0xE771,
        Cone = 0xE98F,
        Console = 0xE756,
        Contact = 0xE12A,
        ContactSend = 0xE1D7,
        Controller = 0xE7FC,
        Copy = 0xE8C8,
        Crop = 0xE123,
        Cursor = 0xE1E3,
        CursorDefault = 0xE8B0,
        Delete = 0xE107,
        Dialer = 0xE75F,
        Diamond = 0xE18A,
        Direction = 0xE816,
        Disk = 0xE105,
        DiskAll = 0xEA35,
        DiskDownload = 0xE159,
        DiskEdit = 0xE28F,
        Divide = 0xE94A,
        Doppler = 0xE95A,
        DotsHorizontal = 0xE10C,
        DotsVertical = 0xE796,
        Download = 0xE118,
        EaseOfAccess = 0xE07F,
        Edit = 0xE104,
        Education = 0xE7BE,
        Email = 0xE119,
        EmailAddress = 0xE168,
        EmailForward = 0xE120,
        EmailForwardRtl = 0xE1A8,
        EmailOpened = 0xE166,
        EmailReply = 0xE172,
        EmailReplyall = 0xE165,
        EmailReplyallRtl = 0xE1F2,
        EmailReplyRtl = 0xE1AF,
        Emoji = 0xE170,
        EmojiGrin = 0xE11D,
        Equal = 0xE94E,
        Eraser = 0xE75C,
        EraserColor1 = 0xE82B,
        EraserColor2 = 0xE82C,
        Exclamation = 0xE171,
        File = 0xE132,
        FileHiddenOutline = 0xE295,
        FileMultiple = 0xE16F,
        FileOutline = 0xE160,
        FileOutlineUp = 0xE8E5,
        FilePrinterOutline = 0xE956,
        Filter = 0xE16E,
        Fingerprint = 0xE928,
        Firewall = 0xE83D,
        Light = 0xEB4F,
        LightChecked = 0xEB50,
        Flash = 0xE945,
        Flashlight = 0xE754,
        Folder = 0xE188,
        FolderMove = 0xE19C,
        FolderOutline = 0xE8B7,
        FolderPlus = 0xE1DA,
        FolderRefresh = 0xE1DF,
        FolderRefreshCancel = 0xE1DD,
        FolderUp = 0xE197,
        FormatBlockLeftDecrease = 0xE290,
        FormatBlockLeftIndent = 0xE291,
        FormatBlockRightDecrease = 0xE297,
        FormatBlockRightIncrease = 0xE298,
        FormatBold = 0xE19B,
        FormatFontSize = 0xE1C8,
        FormatFontSizeDecrease = 0xE1C6,
        FormatFontSizeIncrease = 0xE1C7,
        FormatTextCenter = 0xE1A1,
        FormatTextLeft = 0xE1A2,
        FormatTextRight = 0xE1A0,
        FormatUnderline = 0xE19A,
        Gps = 0xE1D2,
        Grid = 0xE80A,
        GridPerspective = 0xE809,
        Headphones = 0xE7F6,
        Headset = 0xE95B,
        Heart = 0xE00B,
        HeartBroken = 0xE007,
        HeartOutline = 0xE006,
        HeartPulse = 0xE95E,
        Help = 0xE11B,
        History = 0xE81C,
        Home = 0xEA8A,
        HomeOutline = 0xE10F,
        HomeTree = 0xE1C3,
        Image = 0xEB9F,
        Indent = 0xE7FD,
        Info = 0xE946,
        InputMarker = 0xE193,
        InputMarkerColor1 = 0xE891,
        InputMarkerColor2 = 0xE82A,
        InputPen = 0xE76D,
        InputPenColor1 = 0xE88F,
        InputPenColor2 = 0xE829,
        Key = 0xE192,
        Keyboard = 0xE087,
        KeyboardDown = 0xE75B,
        KeyboardEnter = 0xE751,
        KeyboardLeft = 0xE763,
        KeyboardMouse = 0xE961,
        KeyboardRight = 0xE764,
        KeyboardSplit = 0xE08F,
        KeyboardUp = 0xE75A,
        Landmark = 0xE825,
        Laptop = 0xE770,
        LaptopMonitor = 0xE7F8,
        LaptopMonitorExtend = 0xE7F7,
        LaptopPrinter = 0xE772,
        LaptopTablet = 0xE212,
        Layers = 0xE81E,
        Led = 0xE781,
        Library = 0xE1D3,
        Lightbulb = 0xEA80,
        LineHorizontal = 0xE0B8,
        Link = 0xE167,
        List = 0xE292,
        ListBlock = 0xE15C,
        ListBlockRtl = 0xEA65,
        ListCheckRtl = 0xEA98,
        ListCollapse = 0xE16A,
        ListExpand = 0xE169,
        ListRtl = 0xE175,
        ListSelect = 0xE179,
        ListSelectRtl = 0xE1EC,
        ListSelectUp = 0xE17D,
        ListSelectUpRtl = 0xE1ED,
        Lock = 0xE1F6,
        Lowercase = 0xE84A,
        Magnify = 0xE1A3,
        MagnifyMinus = 0xE1A4,
        MagnifyPlus = 0xE12E,
        MapDownload = 0xE826,
        MapLocation = 0xE1C4,
        MapMarkerPause = 0xEB4A,
        MapMarkerPauseOutline = 0xE81A,
        MapMarkerPlay = 0xEB49,
        MapMarkerPlayOutline = 0xE819,
        MapPin = 0xE139,
        Media = 0xEA69,
        MediaFastforward = 0xEB9D,
        MediaNext = 0xE101,
        MediaPause = 0xE103,
        MediaPlay = 0xE102,
        MediaPlayer = 0xE955,
        MediaPrevious = 0xE100,
        MediaRepeat = 0xE1CA,
        MediaRewind = 0xEB9E,
        MediaServer = 0xE953,
        MediaWireless = 0xE952,
        Megaphone = 0xE789,
        Menu = 0xE700,
        Message = 0xE15F,
        MessageForwardRtl = 0xE89B,
        MessageMultiple = 0xE8F2,
        MessageProcessing = 0xE25C,
        MessageQuote = 0xE134,
        MessageVideo = 0xE13B,
        Microphone = 0xE1D6,
        Minus = 0xE108,
        Monitor = 0xE7F4,
        MonitorDuplicate = 0xE7F9,
        MonitorExtend = 0xE7FA,
        MonitorSound = 0xE7F3,
        MonitorTape = 0xE954,
        Moon = 0xE708,
        Mouse = 0xE962,
        Multiply = 0xE947,
        Music = 0xE189,
        Network = 0xE17B,
        NetworkClose = 0xE17A,
        NewWindow = 0xE78B,
        Nfc = 0xE9A1,
        Note = 0xE70B,
        OpenInApp = 0xE17C,
        Outline = 0xE12F,
        OutlineRtl = 0xEA41,
        Palette = 0xE2B1,
        PanelBottom = 0xE147,
        PanelLeft = 0xE145,
        PanelRight = 0xE146,
        Pen = 0xE929,
        Percent = 0xE94C,
        People = 0xE716,
        Phone = 0xE13A,
        PhoneBook = 0xE1D4,
        PhoneForward = 0xE7F2,
        PhoneForwardRtl = 0xEA97,
        PhoneHangup = 0xE137,
        Pin = 0xE840,
        PinColor = 0xE842,
        PinLeft = 0xE141,
        PinLeftColor = 0xE841,
        Plus = 0xE109,
        PlusMinus = 0xE94D,
        Printer = 0xE2F6,
        Printer3d = 0xE2F7,
        Processor = 0xE950,
        Projector = 0xE95D,
        ProtectedDocument = 0xE8A6,
        Puzzle = 0xEA86,
        Redo = 0xE10D,
        Refresh = 0xE117,
        Region = 0xE775,
        Remote = 0xE951,
        Rename = 0xE13E,
        Repeat = 0xE1CD,
        RepeatOnce = 0xE1CC,
        RotateClockwise = 0xE7AD,
        RotateLeft = 0xE14F,
        RotationLock = 0xE755,
        Router = 0xE965,
        RouterWireless = 0xE969,
        Scanner = 0xE294,
        Scissors = 0xE8C6,
        Sd = 0xE7F1,
        Search = 0xE094,
        Security = 0xE727,
        SecurityAlert = 0xE1DE,
        SelectionCut = 0xE924,
        SelectionRedo = 0xE1F4,
        SelectionUndo = 0xE1C5,
        SelectTable = 0xE14E,
        Send = 0xE122,
        Server = 0xE83B,
        ServerNetwork = 0xE968,
        Setting = 0xE115,
        Share = 0xE72D,
        Shuffle = 0xE14B,
        SidebarLeft_expand = 0xE1C0,
        SidebarLeftCollapse = 0xE1BF,
        SidebarRightCollapse = 0xE126,
        SidebarRightExpand = 0xE127,
        Signal1 = 0xE86C,
        Signal2 = 0xE86D,
        Signal3 = 0xE86E,
        Signal4 = 0xE86F,
        Signal5 = 0xE870,
        SignalCancel = 0xE871,
        SlashForward = 0xE199,
        Sound = 0xE15D,
        Sound0 = 0xE992,
        Sound1 = 0xE993,
        Sound2 = 0xE994,
        Sound3 = 0xE995,
        SoundCancel = 0xE198,
        Space = 0xE75D,
        Speaker = 0xE7F5,
        SquareRoot = 0xE94B,
        Star = 0xE1CF,
        StarCancel = 0xE195,
        StarHalfLeft = 0xE7C6,
        StarHalfRight = 0xE7C7,
        StarOutline = 0xE1CE,
        Sun = 0xE706,
        Tablet = 0xE70A,
        Tag = 0xE1CB,
        Tape = 0xE96A,
        ThoughtBubble = 0xEA91,
        Thumbs = 0xE19D,
        ThumbsDown = 0xE19E,
        ThumbsUp = 0xE19F,
        Timer = 0xE916,
        Toolbox = 0xEB4E,
        ToolboxOutline = 0xE821,
        Tooltip = 0xE7E7,
        TooltipOutline = 0xE91C,
        Touch = 0xE815,
        TouchSlider = 0xE927,
        Tram = 0xEB4D,
        TramOutline = 0xE7C0,
        Train = 0xE7C0,
        Translate = 0xE164,
        Undo = 0xE10E,
        Unlock = 0xE1F7,
        Upload = 0xE11C,
        Uppercase = 0xE84B,
        Usb = 0xE88E,
        Video = 0xE25D,
        VideoOutline = 0xE116,
        Voicemail = 0xE1D5,
        Walk = 0xE726,
        WalkOutline = 0xE805,
        Webcam = 0xE960,
        Wifi1 = 0xE872,
        Wifi2 = 0xE873,
        Wifi3 = 0xE874,
        WifiOutline0 = 0xE1E5,
        WifiOutline1 = 0xE1E6,
        WifiOutline2 = 0xE1E7,
        WifiOutline3 = 0xE1E8,
        WifiOutline4 = 0xE1E9,
        WindowCollapse = 0xE1D8,
        WindowExpand = 0xE1D9,
        Wireless = 0xE704,
        World = 0xE128,
        WorldWire = 0xE12B,
        Wrench = 0xE15E,
        Xbox = 0xE990,
    }

    /// <summary>
    /// Proviedes constants to the system icons based on the font MDL2
    /// </summary>
    /// <see cref="http://metronuggets.com/2015/05/18/introducing-mdl2-helpers/"/>
    /// <remarks>
    /// Taken from <see cref="http://metronuggets.com/2015/05/18/introducing-mdl2-helpers/"/>.
    /// Cheetsheet available at <seealso cref="http://modernicons.io/segoe-mdl2/cheatsheet/"/>.
    /// Keep in mind:
    /// When a FontIcon is set in C# code at runtime, we have to use '\uE123;' instad of '&#xE123'.
    /// </remarks>
    public static class SystemIcons
    {
        /// <summary>
        /// The system icon font Segoe MDL2.
        /// </summary>
        public static readonly FontFamily Font = new FontFamily("Segoe MDL2 Assets");

        /// <summary>
        /// The font symbols as hex strings.
        /// </summary>
        public static class Strings
        {
            public static string Account => "&xEA8C;";
            public static string AccountBox => "&xE187;";
            public static string AccountCancel => "&xE1E0;";
            public static string AccountDetailsOutline => "&xE136;";
            public static string AccountFrameOutline => "&xE156;";
            public static string AccountMultiple => "&xE125;";
            public static string AccountOutline => "&xE13D;";
            public static string AccountOutlineBox => "&xE8D4;";
            public static string AccountPlus => "&xE1E2;";
            public static string AccountStatus => "&xE181;";
            public static string AccountSwitch => "&xE748;";
            public static string Airplane => "&xEB4C;";
            public static string AirplaneOutline => "&xE709;";
            public static string Album => "&xE142;";
            public static string Alert => "&xE814;";
            public static string AlertOutline => "&xE7BA;";
            public static string Archive => "&xE7B8;";
            public static string Arrow => "&xE1D1;";
            public static string ArrowBottomRight => "&xE741;";
            public static string ArrowDown => "&xE1FD;";
            public static string ArrowLeft => "&xE0A6;";
            public static string ArrowRight => "&xE0AD;";
            public static string ArrowTopLeft => "&xE742;";
            public static string ArrowUp => "&xE110;";
            public static string ArrowUpVariant => "&xE752;";
            public static string Attach => "&xE16C;";
            public static string BackToWindows => "&xE73F;";
            public static string Bag => "&xE14D;";
            public static string Battery0 => "&xE850;";
            public static string Battery1 => "&xE851;";
            public static string Battery10 => "&xE83F;";
            public static string Battery2 => "&xE852;";
            public static string Battery3 => "&xE853;";
            public static string Battery4 => "&xE854;";
            public static string Battery5 => "&xE855;";
            public static string Battery6 => "&xE856;";
            public static string Battery7 => "&xE857;";
            public static string Battery8 => "&xE858;";
            public static string Battery9 => "&xE859;";
            public static string BatteryCharge0 => "&xE85A;";
            public static string BatteryCharge1 => "&xE85B;";
            public static string BatteryCharge2 => "&xE85C;";
            public static string BatteryCharge3 => "&xE85D;";
            public static string BatteryCharge4 => "&xE85E;";
            public static string BatteryCharge5 => "&xE85F;";
            public static string BatteryCharge6 => "&xE860;";
            public static string BatteryCharge7 => "&xE861;";
            public static string BatteryCharge8 => "&xE862;";
            public static string BatteryDisconnect => "&xE996;";
            public static string BatteryLarge0 => "&xEBA0;";
            public static string BatteryLarge1 => "&xEBA1;";
            public static string BatteryLarge10 => "&xEBAA;";
            public static string BatteryLarge2 => "&xEBA2;";
            public static string BatteryLarge3 => "&xEBA3;";
            public static string BatteryLarge4 => "&xEBA4;";
            public static string BatteryLarge5 => "&xEBA5;";
            public static string BatteryLarge6 => "&xEBA6;";
            public static string BatteryLarge7 => "&xEBA7;";
            public static string BatteryLarge8 => "&xEBA8;";
            public static string BatteryLarge9 => "&xEBA9;";
            public static string BatteryLargeCharge0 => "&xEBAB;";
            public static string BatteryLargeCharge1 => "&xEBAC;";
            public static string BatteryLargeCharge10 => "&xEBB5;";
            public static string BatteryLargeCharge2 => "&xEBAD;";
            public static string BatteryLargeCharge3 => "&xEBAE;";
            public static string BatteryLargeCharge4 => "&xEBAF;";
            public static string BatteryLargeCharge5 => "&xEBB0;";
            public static string BatteryLargeCharge6 => "&xEBB1;";
            public static string BatteryLargeCharge7 => "&xEBB2;";
            public static string BatteryLargeCharge8 => "&xEBB3;";
            public static string BatteryLargeCharge9 => "&xEBB4;";
            public static string BatteryLargeSave0 => "&xEBB6;";
            public static string BatteryLargeSave1 => "&xEBB7;";
            public static string BatteryLargeSave10 => "&xEBC0;";
            public static string BatteryLargeSave2 => "&xEBB8;";
            public static string BatteryLargeSave3 => "&xEBB9;";
            public static string BatteryLargeSave4 => "&xEBBA;";
            public static string BatteryLargeSave5 => "&xEBBB;";
            public static string BatteryLargeSave6 => "&xEBBC;";
            public static string BatteryLargeSave7 => "&xEBBD;";
            public static string BatteryLargeSave8 => "&xEBBE;";
            public static string BatteryLargeSave9 => "&xEBBF;";
            public static string BatterySave0 => "&xE863;";
            public static string BatterySave1 => "&xE864;";
            public static string BatterySave2 => "&xE865;";
            public static string BatterySave3 => "&xE866;";
            public static string BatterySave4 => "&xE867;";
            public static string BatterySave5 => "&xE868;";
            public static string BatterySave6 => "&xE869;";
            public static string BatterySave7 => "&xE86A;";
            public static string BatterySave8 => "&xE86B;";
            public static string BellOffOutline => "&xE7ED;";
            public static string BellOutline => "&xEA8F;";
            public static string Bluetooth => "&xE702;";
            public static string Boat => "&xEB48;";
            public static string BoatOutline => "&xE7E3;";
            public static string Book => "&xE82D;";
            public static string BookPlus => "&xE82E;";
            public static string BoxFourth => "&xE744;";
            public static string BoxFull => "&xE747;";
            public static string BoxHalfHorizontal => "&xE745;";
            public static string BoxHalfVertical => "&xE746;";
            public static string BoxSixteenth => "&xE743;";
            public static string BoxSmall => "&xE004;";
            public static string Bus => "&xEB47;";
            public static string BusOutline => "&xE806;";
            public static string Calculator => "&xE1D0;";
            public static string Calendar => "&xE163;";
            public static string CalendarDay => "&xE184;";
            public static string CalendarRepeat => "&xE161;";
            public static string CalendarReply => "&xE1DB;";
            public static string CalendarWeeks => "&xE162;";
            public static string Camera => "&xE114;";
            public static string CameraClicker => "&xE12D;";
            public static string CameraSwitch => "&xE124;";
            public static string Cancel => "&xE25B;";
            public static string Car => "&xE7EC;";
            public static string CarLeftOutline => "&xE811;";
            public static string CarRightOutline => "&xEA5E;";
            public static string CarSide => "&xEA8B;";
            public static string Cd => "&xE958;";
            public static string Cellphone => "&xE1C9;";
            public static string CellphoneTablet => "&xE8CC;";
            public static string CellphoneWireless => "&xE957;";
            public static string Check => "&xE001;";
            public static string CheckboxBlank => "&xE002;";
            public static string CheckboxBlankOutline => "&xE003;";
            public static string CheckboxCheck => "&xE005;";
            public static string CheckOutlineCheck => "&xE0A2;";
            public static string ChevronBoldDown => "&xE96E;";
            public static string ChevronBoldLeft => "&xE96F;";
            public static string ChevronBoldRight => "&xE970;";
            public static string ChevronBoldUp => "&xE96D;";
            public static string ChevronDown => "&xE011;";
            public static string ChevronLeft => "&xE00E;";
            public static string ChevronLeftCircle => "&xE760;";
            public static string ChevronRight => "&xE00F;";
            public static string ChevronRightCircle => "&xE761;";
            public static string ChevronUp => "&xE010;";
            public static string Chip => "&xE964;";
            public static string Clear => "&xE750;";
            public static string ClearSmall => "&xE925;";
            public static string Clipboard => "&xE77F;";
            public static string Clock => "&xE121;";
            public static string Close => "&xE106;";
            public static string ClosedCaption => "&xE190;";
            public static string Cloud => "&xE753;";
            public static string Compare => "&xE11E;";
            public static string Computer => "&xE211;";
            public static string ComputerTheme => "&xE771;";
            public static string Cone => "&xE98F;";
            public static string Console => "&xE756;";
            public static string Contact => "&xE12A;";
            public static string ContactSend => "&xE1D7;";
            public static string Controller => "&xE7FC;";
            public static string Crop => "&xE123;";
            public static string Cursor => "&xE1E3;";
            public static string CursorDefault => "&xE8B0;";
            public static string Delete => "&xE107;";
            public static string Dialer => "&xE75F;";
            public static string Diamond => "&xE18A;";
            public static string Direction => "&xE816;";
            public static string Disk => "&xE105;";
            public static string DiskAll => "&xEA35;";
            public static string DiskDownload => "&xE159;";
            public static string DiskEdit => "&xE28F;";
            public static string Divide => "&xE94A;";
            public static string Doppler => "&xE95A;";
            public static string DotsHorizontal => "&xE10C;";
            public static string DotsVertical => "&xE796;";
            public static string Download => "&xE118;";
            public static string EaseOfAccess => "&xE07F;";
            public static string Edit => "&xE104;";
            public static string Education => "&xE7BE;";
            public static string Email => "&xE119;";
            public static string EmailAddress => "&xE168;";
            public static string EmailForward => "&xE120;";
            public static string EmailForwardRtl => "&xE1A8;";
            public static string EmailOpened => "&xE166;";
            public static string EmailReply => "&xE172;";
            public static string EmailReplyall => "&xE165;";
            public static string EmailReplyallRtl => "&xE1F2;";
            public static string EmailReplyRtl => "&xE1AF;";
            public static string Emoji => "&xE170;";
            public static string EmojiGrin => "&xE11D;";
            public static string Equal => "&xE94E;";
            public static string Eraser => "&xE75C;";
            public static string EraserColor1 => "&xE82B;";
            public static string EraserColor2 => "&xE82C;";
            public static string Exclamation => "&xE171;";
            public static string File => "&xE132;";
            public static string FileHiddenOutline => "&xE295;";
            public static string FileMultiple => "&xE16F;";
            public static string FileOutline => "&xE160;";
            public static string FileOutlineUp => "&xE8E5;";
            public static string FilePrinterOutline => "&xE956;";
            public static string Filter => "&xE16E;";
            public static string Fingerprint => "&xE928;";
            public static string Firewall => "&xE83D;";
            public static string Flag => "&xEB4F;";
            public static string FlagOutline => "&xEB50;";
            public static string Flash => "&xE945;";
            public static string Flashlight => "&xE754;";
            public static string Folder => "&xE188;";
            public static string FolderMove => "&xE19C;";
            public static string FolderOutline => "&xE8B7;";
            public static string FolderPlus => "&xE1DA;";
            public static string FolderRefresh => "&xE1DF;";
            public static string FolderRefreshCancel => "&xE1DD;";
            public static string FolderUp => "&xE197;";
            public static string FormatBlockLeftDecrease => "&xE290;";
            public static string FormatBlockLeftIndent => "&xE291;";
            public static string FormatBlockRightDecrease => "&xE297;";
            public static string FormatBlockRightIncrease => "&xE298;";
            public static string FormatBold => "&xE19B;";
            public static string FormatFontSize => "&xE1C8;";
            public static string FormatFontSizeDecrease => "&xE1C6;";
            public static string FormatFontSizeIncrease => "&xE1C7;";
            public static string FormatTextCenter => "&xE1A1;";
            public static string FormatTextLeft => "&xE1A2;";
            public static string FormatTextRight => "&xE1A0;";
            public static string FormatUnderline => "&xE19A;";
            public static string FullScreen => "&xE740;";
            public static string Gps => "&xE1D2;";
            public static string Grid => "&xE80A;";
            public static string GridPerspective => "&xE809;";
            public static string Headphones => "&xE7F6;";
            public static string Headset => "&xE95B;";
            public static string Heart => "&xE00B;";
            public static string HeartBroken => "&xE007;";
            public static string HeartOutline => "&xE006;";
            public static string HeartPulse => "&xE95E;";
            public static string Help => "&xE11B;";
            public static string History => "&xE81C;";
            public static string Home => "&xEA8A;";
            public static string HomeOutline => "&xE10F;";
            public static string HomeTree => "&xE1C3;";
            public static string Image => "&xEB9F;";
            public static string Indent => "&xE7FD;";
            public static string Info => "&xE946;";
            public static string InputMarker => "&xE193;";
            public static string InputMarkerColor1 => "&xE891;";
            public static string InputMarkerColor2 => "&xE82A;";
            public static string InputPen => "&xE76D;";
            public static string InputPenColor1 => "&xE88F;";
            public static string InputPenColor2 => "&xE829;";
            public static string Key => "&xE192;";
            public static string Keyboard => "&xE087;";
            public static string KeyboardDown => "&xE75B;";
            public static string KeyboardEnter => "&xE751;";
            public static string KeyboardLeft => "&xE763;";
            public static string KeyboardMouse => "&xE961;";
            public static string KeyboardRight => "&xE764;";
            public static string KeyboardSplit => "&xE08F;";
            public static string KeyboardUp => "&xE75A;";
            public static string Landmark => "&xE825;";
            public static string Laptop => "&xE770;";
            public static string LaptopMonitor => "&xE7F8;";
            public static string LaptopMonitorExtend => "&xE7F7;";
            public static string LaptopPrinter => "&xE772;";
            public static string LaptopTablet => "&xE212;";
            public static string Layers => "&xE81E;";
            public static string Led => "&xE781;";
            public static string Library => "&xE1D3;";
            public static string Lightbulb => "&xEA80;";
            public static string LineHorizontal => "&xE0B8;";
            public static string Link => "&xE167;";
            public static string List => "&xE292;";
            public static string ListBlock => "&xE15C;";
            public static string ListBlockRtl => "&xEA65;";
            public static string ListCheckRtl => "&xEA98;";
            public static string ListCollapse => "&xE16A;";
            public static string ListExpand => "&xE169;";
            public static string ListRtl => "&xE175;";
            public static string ListSelect => "&xE179;";
            public static string ListSelectRtl => "&xE1EC;";
            public static string ListSelectUp => "&xE17D;";
            public static string ListSelectUpRtl => "&xE1ED;";
            public static string Lock => "&xE1F6;";
            public static string Lowercase => "&xE84A;";
            public static string Magnify => "&xE1A3;";
            public static string MagnifyMinus => "&xE1A4;";
            public static string MagnifyPlus => "&xE12E;";
            public static string MapDownload => "&xE826;";
            public static string MapLocation => "&xE1C4;";
            public static string MapMarkerPause => "&xEB4A;";
            public static string MapMarkerPauseOutline => "&xE81A;";
            public static string MapMarkerPlay => "&xEB49;";
            public static string MapMarkerPlayOutline => "&xE819;";
            public static string MapPin => "&xE139;";
            public static string Media => "&xEA69;";
            public static string MediaFastforward => "&xEB9D;";
            public static string MediaNext => "&xE101;";
            public static string MediaPause => "&xE103;";
            public static string MediaPlay => "&xE102;";
            public static string MediaPlayer => "&xE955;";
            public static string MediaPrevious => "&xE100;";
            public static string MediaRepeat => "&xE1CA;";
            public static string MediaRewind => "&xEB9E;";
            public static string MediaServer => "&xE953;";
            public static string MediaWireless => "&xE952;";
            public static string Megaphone => "&xE789;";
            public static string Menu => "&xE700;";
            public static string Message => "&xE15F;";
            public static string MessageForwardRtl => "&xE89B;";
            public static string MessageMultiple => "&xE8F2;";
            public static string MessageProcessing => "&xE25C;";
            public static string MessageQuote => "&xE134;";
            public static string MessageVideo => "&xE13B;";
            public static string Microphone => "&xE1D6;";
            public static string Minus => "&xE108;";
            public static string Monitor => "&xE7F4;";
            public static string MonitorDuplicate => "&xE7F9;";
            public static string MonitorExtend => "&xE7FA;";
            public static string MonitorSound => "&xE7F3;";
            public static string MonitorTape => "&xE954;";
            public static string Moon => "&xE708;";
            public static string Mouse => "&xE962;";
            public static string Multiply => "&xE947;";
            public static string Music => "&xE189;";
            public static string Network => "&xE17B;";
            public static string NetworkClose => "&xE17A;";
            public static string NewWindow => "&xE78B;";
            public static string Nfc => "&xE9A1;";
            public static string Note => "&xE70B;";
            public static string OpenInApp => "&xE17C;";
            public static string Outline => "&xE12F;";
            public static string OutlineRtl => "&xEA41;";
            public static string Palette => "&xE2B1;";
            public static string PanelBottom => "&xE147;";
            public static string PanelLeft => "&xE145;";
            public static string PanelRight => "&xE146;";
            public static string Pen => "&xE929;";
            public static string Percent => "&xE94C;";
            public static string Phone => "&xE13A;";
            public static string PhoneBook => "&xE1D4;";
            public static string PhoneForward => "&xE7F2;";
            public static string PhoneForwardRtl => "&xEA97;";
            public static string PhoneHangup => "&xE137;";
            public static string Pin => "&xE840;";
            public static string PinColor => "&xE842;";
            public static string PinLeft => "&xE141;";
            public static string PinLeftColor => "&xE841;";
            public static string Plus => "&xE109;";
            public static string PlusMinus => "&xE94D;";
            public static string Printer => "&xE2F6;";
            public static string Printer3d => "&xE2F7;";
            public static string Processor => "&xE950;";
            public static string Projector => "&xE95D;";
            public static string Puzzle => "&xEA86;";
            public static string Redo => "&xE10D;";
            public static string Refresh => "&xE117;";
            public static string Region => "&xE775;";
            public static string Remote => "&xE951;";
            public static string Rename => "&xE13E;";
            public static string Repeat => "&xE1CD;";
            public static string RepeatOnce => "&xE1CC;";
            public static string RotateClockwise => "&xE7AD;";
            public static string RotateLeft => "&xE14F;";
            public static string RotationLock => "&xE755;";
            public static string Router => "&xE965;";
            public static string RouterWireless => "&xE969;";
            public static string Scanner => "&xE294;";
            public static string Scissors => "&xE8C6;";
            public static string Sd => "&xE7F1;";
            public static string Search => "&xE094;";
            public static string Security => "&xE727;";
            public static string SecurityAlert => "&xE1DE;";
            public static string SelectionCut => "&xE924;";
            public static string SelectionRedo => "&xE1F4;";
            public static string SelectionUndo => "&xE1C5;";
            public static string SelectTable => "&xE14E;";
            public static string Send => "&xE122;";
            public static string Server => "&xE83B;";
            public static string ServerNetwork => "&xE968;";
            public static string Setting => "&xE115;";
            public static string Share => "&xE72D;";
            public static string Shuffle => "&xE14B;";
            public static string SidebarLeft_expand => "&xE1C0;";
            public static string SidebarLeftCollapse => "&xE1BF;";
            public static string SidebarRightCollapse => "&xE126;";
            public static string SidebarRightExpand => "&xE127;";
            public static string Signal1 => "&xE86C;";
            public static string Signal2 => "&xE86D;";
            public static string Signal3 => "&xE86E;";
            public static string Signal4 => "&xE86F;";
            public static string Signal5 => "&xE870;";
            public static string SignalCancel => "&xE871;";
            public static string SlashForward => "&xE199;";
            public static string Sound => "&xE15D;";
            public static string Sound0 => "&xE992;";
            public static string Sound1 => "&xE993;";
            public static string Sound2 => "&xE994;";
            public static string Sound3 => "&xE995;";
            public static string SoundCancel => "&xE198;";
            public static string Space => "&xE75D;";
            public static string Speaker => "&xE7F5;";
            public static string SquareRoot => "&xE94B;";
            public static string Star => "&xE1CF;";
            public static string StarCancel => "&xE195;";
            public static string StarHalfLeft => "&xE7C6;";
            public static string StarHalfRight => "&xE7C7;";
            public static string StarOutline => "&xE1CE;";
            public static string Sun => "&xE706;";
            public static string Tablet => "&xE70A;";
            public static string Tag => "&xE1CB;";
            public static string Tape => "&xE96A;";
            public static string ThoughtBubble => "&xEA91;";
            public static string Thumbs => "&xE19D;";
            public static string ThumbsDown => "&xE19E;";
            public static string ThumbsUp => "&xE19F;";
            public static string Timer => "&xE916;";
            public static string Toolbox => "&xEB4E;";
            public static string ToolboxOutline => "&xE821;";
            public static string Tooltip => "&xE7E7;";
            public static string TooltipOutline => "&xE91C;";
            public static string Touch => "&xE815;";
            public static string TouchSlider => "&xE927;";
            public static string Tram => "&xEB4D;";
            public static string TramOutline => "&xE7C0;";
            public static string Translate => "&xE164;";
            public static string Undo => "&xE10E;";
            public static string Unlock => "&xE1F7;";
            public static string Upload => "&xE11C;";
            public static string Uppercase => "&xE84B;";
            public static string Usb => "&xE88E;";
            public static string Video => "&xE25D;";
            public static string VideoOutline => "&xE116;";
            public static string Voicemail => "&xE1D5;";
            public static string Walk => "&xE726;";
            public static string WalkOutline => "&xE805;";
            public static string Webcam => "&xE960;";
            public static string Wifi1 => "&xE872;";
            public static string Wifi2 => "&xE873;";
            public static string Wifi3 => "&xE874;";
            public static string WifiOutline0 => "&xE1E5;";
            public static string WifiOutline1 => "&xE1E6;";
            public static string WifiOutline2 => "&xE1E7;";
            public static string WifiOutline3 => "&xE1E8;";
            public static string WifiOutline4 => "&xE1E9;";
            public static string WindowCollapse => "&xE1D8;";
            public static string WindowExpand => "&xE1D9;";
            public static string Wireless => "&xE704;";
            public static string World => "&xE128;";
            public static string WorldWire => "&xE12B;";
            public static string Wrench => "&xE15E;";
            public static string Xbox => "&xE990;";
        }

        /// <summary>
        /// The font symbols as characters for <see cref="FontIcon"/> controls.
        /// </summary>
        public static class Chars
        {
            /// <summary>
            /// Converts the character from a symbol.
            /// </summary>
            /// <param name="symbol">The symbol enum value.</param>
            /// <returns>The character.</returns>
            public static char FromSymbol(Symbol symbol)
            {
                return (char)symbol;
            }

            /// <summary>
            /// Converts the character from a glyph icon.
            /// </summary>
            /// <param name="glyphIcon">The glyph icon enum value.</param>
            /// <returns>The character.</returns>
            public static char FromSymbol(GlyphIcons glyphIcon)
            {
                return (char)glyphIcon;
            }
        }
    }
}
